export const SET_AUTH_USER = 'SET_AUTH_USER'
export const UNSET_AUTH_USER = 'UNSET_AUTH_USER'

export const GET_BLOG = 'GET_BLOG'
export const GET_MY_BLOG = 'GET_MY_BLOG'
export const BLOG_LIST = 'BLOG_LIST'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const GET_TAGS = 'GET_TAGS'

export const SHOW_COMMENT_AREA = 'SHOW_COMMENT_AREA'
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'
export const ADD_COMMENT_LIST = 'ADD_COMMENT_LIST'
export const GET_MY_COMMENT = 'GET_MY_COMMENT'

export const GENERATE_ACCOUNT_INFO = 'GENERATE_ACCOUNT_INFO'
export const SET_USER_INFO = 'SET_USER_INFO'
